name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ "bitmap", "ctrlc", "grrs", "guessing_game", "reverse", "ssh-config", "sqlite", "to-do" ]

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: cargo build --verbose
      working-directory: ${{ matrix.project }}

    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ matrix.project }}
